Python 3.14.3 (v3.14.3:323c59a5e34, Feb  3 2026, 11:41:37) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Enter "help" below or click "Help" above for more information.
>>> import streamlit as st
... 
... st.set_page_config(page_title="AI Resume Analyzer")
... 
... st.title("AI Resume Analyzer")
... 
... st.write("If you see this message, deployment is working.")
... 
... uploaded_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"])
... 
... job_desc = st.text_area("Paste Job Description")
... 
... if st.button("Analyze"):
